### ISSUE TITLE
Getting this to work with livereload

### ISSUE THREAD

**Issue by jme783** [ericf/express-handlebars#116]
Hi there!

Thanks for the library, super awesome! I was wondering if there was a way to get this working with live reload to avoid having to stop/restart the server every time a `.hbs` file changes. Currently, I'm using Grunt and would love to trigger livereload based on when a handlebars file changes.

Thanks!

Jeff

**Comment by ericf** [comment]
When the node process and Express app are in development mode (which is is by default), the templates are _always_ loaded from disk every request. So it sounds like you'll want to setup your live reload config to only refresh the browser when a template changes, but not restart the server since that won't be necessary.

**Comment by jme783** [comment]
Oh awesome, thanks @ericf appreciate the answer. I'll close out the ticket.
